plugins:
  - jekyll-paginate

title: Emma's Blog
description: Decipher the code of ecology and evolution with codes.
url: "https://tripleemma.github.io"
author: "Emma"

excerpt_separator: "<!--more-->"
paginate: 6
paginate_path: /page/:num/
permalink: /:title/
